"""Add password column on users

Revision ID: 732adb140f84
Revises: 0ef92e315daf
Create Date: 2023-10-01 13:22:10.949746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732adb140f84'
down_revision = '0ef92e315daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True, comment='ハッシュ化されたパスワード'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
