"""empty message

Revision ID: 914a515d9521
Revises: 
Create Date: 2023-09-17 09:58:39.826413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914a515d9521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='アカウント情報'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
