"""add account_deletions table

Revision ID: e27e4853f23e
Revises: f2ea6b227285
Create Date: 2023-09-21 13:50:08.099408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27e4853f23e'
down_revision = 'f2ea6b227285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_deletions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('account_id', sa.String(length=26), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False, comment='退会日時'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='アカウントの削除情報'
    )
    with op.batch_alter_table('account_deletions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_deletions_account_id'), ['account_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_deletions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_deletions_account_id'))

    op.drop_table('account_deletions')
    # ### end Alembic commands ###
